/**
 * Builds the DSH host plugin bundle.
 *
 * The adapter itself is TypeScript, and DSH loads plain ESM from the installed
 * package, so `adapters/dsh/index.ts` is bundled into `dist/dsh/bundle.js`.
 * Everything except Node builtins is inlined (including picomatch), because a
 * plugin installed into a profile cannot resolve `@deepseek-ai/*` packages —
 * and this way it needs no runtime dependencies at all.
 *
 * `dist/dsh/plugin.js` (the package entry) is a tiny stable shim that imports
 * the bundle with a cache-busting query. Node caches ESM by URL, so without it
 * a rebuilt plugin could never be re-enabled in a running DSH process.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { build } from "esbuild";

const OUT_DIR = "dist/dsh";

mkdirSync(OUT_DIR, { recursive: true });

await build({
	entryPoints: ["adapters/dsh/index.ts"],
	outfile: `${OUT_DIR}/bundle.js`,
	bundle: true,
	format: "esm",
	platform: "node",
	target: "node20",
	legalComments: "none",
	logLevel: "info",
});

writeFileSync(
	`${OUT_DIR}/plugin.js`,
	`// Generated by scripts/build-dsh.mjs — loads the current bundle.
const mod = await import(\`./bundle.js?t=\${Date.now()}\`);
export const name = mod.name;
export const inject = mod.inject;
export const apply = mod.apply;
`,
);
